import "../globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`flex flex-col items-center justify-center h-screen w-full`}>
        {children}
      </body>
    </html>
  );
}
