import localFont from "next/font/local";
import "../globals.css";
import Navigation from "@/component/navigation";
import TopNav from "@/component/TopNav";
import Container from "@/component/Container";

const iransans = localFont({
  src: [

    {
      path: "../fonts/IRANSansWebFaNum_Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansWebFaNum.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansWebFaNum_Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansWebFaNum_Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansWebFaNum_Black.woff",
      weight: "900",
      style: "normal",
    },
  ],
  variable: '--font-iransans',
  display: 'swap',
});



export const metadata = {
  title: "Music App",
  description: "Generated by create next app",
};


export default function MusicLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iransans.variable} antialiased bg-black`}>
      <div className="flex flex-col lg:flex-row h-screen">
        <Navigation />
        <div className="flex-1 overflow-auto">
          <Container className="mt-2 pb-10">
            <TopNav />
            {children}
          </Container >
        </div>
      </div>
      </body>
    </html>
  );
}
